
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gestion_ceramica_development

test:
  <<: *default
  database: gestion_ceramica_test

# production:
#   <<: *default
#   database: gestion_ceramica_production
#   username: gestion_ceramica
#   password: <%= ENV["GESTION_CERAMICA_DATABASE_PASSWORD"] %>
